# Generated by Django 3.2.5 on 2021-08-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20210801_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='allowed_attempts',
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='date',
        ),
    ]
