# Generated by Django 3.2.5 on 2021-08-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20210802_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='time_limit_mins',
        ),
    ]
